### ISSUE TITLE
Blue-Submarine GTK-3.0 image issue.

### ISSUE THREAD

**Issue by tefletch** [raveit65/mate-themes-extras#7]
When I run my GTK3 application under the Blue-Submarine theme, I get the following warning:

>Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Blue-Submarine/gtk-3.0/assets/checkbox-menuitem-unchecked.svg': Unrecognized image file format

When I take a look at the image "assets" directory, that particular SVG file is suspiciously larger than its counterparts.  When I change to another theme, my application no longer complains.  My desktop is ubuntu-mate (16.04).

**Comment by raveit65** [comment]
Blue-Submarine is moved to mate-themes since a long time.
